name: Build and Test flask application

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Flask
        run: pip install flask

      - name: Run Flask Application
        run: python app.py &
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Set executable permission
        run: chmod +x test_app.py

      - name: Install Flask
        run: pip install flask

      - name: Install pytest
        run: pip install pytest


      - name: Test Python code
        run: pytest test_app.py
        
      - name: Create version 1.0
        run: |
          git tag -a v1.0 -m "Version 1.0 release"
          git push origin v1.0


      - name: Deploy to dev environment
        uses: mohanvedase/github-release-action@v1.0.1
        with:
          repo:  mohanvedase/cicd_GitHubActions.git 
          token: ${{ secrets.DEPLOY_TOKEN }}
          branch: dev
          release_name: ${{ github.sha }}

